import { PinyinCategory, PinyinChar } from './types';

export const INITIALS: PinyinChar[] = [
  { char: 'b', category: PinyinCategory.INITIALS },
  { char: 'p', category: PinyinCategory.INITIALS },
  { char: 'm', category: PinyinCategory.INITIALS },
  { char: 'f', category: PinyinCategory.INITIALS },
  { char: 'd', category: PinyinCategory.INITIALS },
  { char: 't', category: PinyinCategory.INITIALS },
  { char: 'n', category: PinyinCategory.INITIALS },
  { char: 'l', category: PinyinCategory.INITIALS },
  { char: 'g', category: PinyinCategory.INITIALS },
  { char: 'k', category: PinyinCategory.INITIALS },
  { char: 'h', category: PinyinCategory.INITIALS },
  { char: 'j', category: PinyinCategory.INITIALS },
  { char: 'q', category: PinyinCategory.INITIALS },
  { char: 'x', category: PinyinCategory.INITIALS },
  { char: 'zh', category: PinyinCategory.INITIALS },
  { char: 'ch', category: PinyinCategory.INITIALS },
  { char: 'sh', category: PinyinCategory.INITIALS },
  { char: 'r', category: PinyinCategory.INITIALS },
  { char: 'z', category: PinyinCategory.INITIALS },
  { char: 'c', category: PinyinCategory.INITIALS },
  { char: 's', category: PinyinCategory.INITIALS },
  { char: 'y', category: PinyinCategory.INITIALS },
  { char: 'w', category: PinyinCategory.INITIALS },
];

export const FINALS: PinyinChar[] = [
  { char: 'a', category: PinyinCategory.FINALS },
  { char: 'o', category: PinyinCategory.FINALS },
  { char: 'e', category: PinyinCategory.FINALS },
  { char: 'i', category: PinyinCategory.FINALS },
  { char: 'u', category: PinyinCategory.FINALS },
  { char: 'ü', category: PinyinCategory.FINALS },
  { char: 'ai', category: PinyinCategory.FINALS },
  { char: 'ei', category: PinyinCategory.FINALS },
  { char: 'ui', category: PinyinCategory.FINALS },
  { char: 'ao', category: PinyinCategory.FINALS },
  { char: 'ou', category: PinyinCategory.FINALS },
  { char: 'iu', category: PinyinCategory.FINALS },
  { char: 'ie', category: PinyinCategory.FINALS },
  { char: 'üe', category: PinyinCategory.FINALS },
  { char: 'er', category: PinyinCategory.FINALS },
  { char: 'an', category: PinyinCategory.FINALS },
  { char: 'en', category: PinyinCategory.FINALS },
  { char: 'in', category: PinyinCategory.FINALS },
  { char: 'un', category: PinyinCategory.FINALS },
  { char: 'ün', category: PinyinCategory.FINALS },
  { char: 'ang', category: PinyinCategory.FINALS },
  { char: 'eng', category: PinyinCategory.FINALS },
  { char: 'ing', category: PinyinCategory.FINALS },
  { char: 'ong', category: PinyinCategory.FINALS },
];

export const OVERALL: PinyinChar[] = [
  { char: 'zhi', category: PinyinCategory.OVERALL },
  { char: 'chi', category: PinyinCategory.OVERALL },
  { char: 'shi', category: PinyinCategory.OVERALL },
  { char: 'ri', category: PinyinCategory.OVERALL },
  { char: 'zi', category: PinyinCategory.OVERALL },
  { char: 'ci', category: PinyinCategory.OVERALL },
  { char: 'si', category: PinyinCategory.OVERALL },
  { char: 'yi', category: PinyinCategory.OVERALL },
  { char: 'wu', category: PinyinCategory.OVERALL },
  { char: 'yu', category: PinyinCategory.OVERALL },
  { char: 'ye', category: PinyinCategory.OVERALL },
  { char: 'yue', category: PinyinCategory.OVERALL },
  { char: 'yuan', category: PinyinCategory.OVERALL },
  { char: 'yin', category: PinyinCategory.OVERALL },
  { char: 'yun', category: PinyinCategory.OVERALL },
  { char: 'ying', category: PinyinCategory.OVERALL },
];
